# Generated by Django 4.1 on 2022-11-09 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('1', 'User'), ('2', 'Instructor')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='My Weight')),
                ('height', models.FloatField(verbose_name='My Height')),
                ('age', models.PositiveIntegerField(verbose_name='My Age')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=7, verbose_name='My Gender')),
                ('calories', models.FloatField()),
                ('water', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('sleep', models.CharField(max_length=20, verbose_name='Sleep Time')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
