# Generated by Django 4.1.2 on 2022-10-28 07:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=tinymce.models.HTMLField(),
        ),
    ]
